### ISSUE TITLE
dify-sandbox   <module> ModuleNotFoundError: No module named 'json' error: exit status 255

### ISSUE THREAD

**Issue by yuruicai-tal** [langgenius/dify-sandbox#172]
求助：源码 docker image部署后代码执行都包同样的错误

错误信息如下：

Traceback (most recent call last): File "/var/sandbox/sandbox-python/tmp/ddf5d3c8_db5c_40e6_bc8e_56a8938a6226.py", line 48, in <module> File "<string>", line 8, in <module> ModuleNotFoundError: No module named 'json' error: exit status 255

谁能告诉我是什么原因。感恩的心～

**Comment by wwwfdisk** [comment]
我不知道原因，不过我是这么解决的。
修改 docker/docker-compose.yaml 中 sandbox 的 配置，添加/var/sandbox路径映射：
I don't know the cause, but I fixed it in this way:
Modify the config of sandbox service in docker/docker-compose.yaml, add volume mapping for /var/sandbox: 

```
sandbox:
  image: langgenius/dify-sandbox:0.2.14
  restart: always
  environment:
    - SANDBOX_PORT=8194
    # 其他环境变量...
  volumes:
    - ./volumes/sandbox/dependencies:/dependencies
    - ./volumes/sandbox/conf:/conf 
    - ./volumes/sandbox/var/sandbox:/var/sandbox    # ✅ 关键：工作目录映射
  ports:
    - "8194:8194"
  ......
```
详细步骤：
1、创建必要的目录：
Create necessary directory:

```
bash

mkdir -p ./volumes/sandbox/var/sandbox
```

2、修改 docker-compose.yaml，添加上述 volumes 配置
Modify docker-compose.yaml, add above volumes configuration

3、重启 sandbox 服务：
Restart sandbox service:

```
bash

docker compose restart sandbox

# 或者完全重建
docker compose up -d --force-recreate sandbox
```

4、验证是否正常工作：
Verify if the code works:
```
bash

# 检查日志，不应该再出现 python lib path 相关的 WARN
docker compose logs sandbox

# 在 Dify 中测试代码执行节点
```
