### ISSUE TITLE
how to import the third packages

### ISSUE THREAD

**Issue by sharptornadoqsh** [langgenius/dify-sandbox#37]
i follow the faq and build the source source code and tag it to a docker。when i use the docker in dify，i can not import the nump 
this is the error
<img width="364" alt="微信图片_20240814155629" src="https://github.com/user-attachments/assets/0d8df1c5-bc9b-4958-a51c-c9d253d4cf10">
<img width="716" alt="微信图片_20240814175624" src="https://github.com/user-attachments/assets/a7210591-4973-4123-a6c1-8f2e4a0e2f9d">
it seems there is some permission problems

**Comment by sharptornadoqsh** [comment]
i follow this setp1 、setp2 to set the config.yaml and zsysnum_linux_amd64.go file
https://github.com/langgenius/dify-sandbox/blob/main/FAQ.md#1-why-does-my-python-code-throw-an-exception-like-xxxso-cannot-open-shared-object-file-no-such-file-or-directory

**Comment by hjlarry** [comment]
try to use numpy 1.x version

**Comment by sharptornadoqsh** [comment]
您好，您的邮件我已经收到，我会尽快处理

**Comment by sharptornadoqsh** [comment]
i reaplace the numpy version and set some .so in config.yaml but the problem in  picture 2 is still there 
2024/08/15 05:25:20 server.go:50: [INFO]initializing python dependencies sandbox...
2024/08/15 05:26:54 env.go:30: [WARN]python lib path /usr/lib/python3.10 is not available
2024/08/15 05:26:54 env.go:30: [WARN]python lib path /usr/lib/python3 is not available
2024/08/15 05:26:54 env.go:30: [WARN]python lib path /run/systemd/resolve/stub-resolv.conf is not available
2024/08/15 05:26:54 env.go:30: [WARN]python lib path /run/resolvconf/resolv.conf is not available
2024/08/15 05:26:54 server.go:55: [INFO]python dependencies sandbox initialized
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middlew

**Comment by hjlarry** [comment]
it seems your python is not in the `/usr/lib/python3.10` or `/usr/lib/python3`, try to fix that first.

**Comment by sharptornadoqsh** [comment]
> it seems your python is not in the `/usr/lib/python3.10` or `/usr/lib/python3`, try to fix that first.

you are right i modify the config.yaml

but new problems

this is the error in dify web：
Node 代码执行 2 run failed: READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE! Importing the numpy C-extensions failed. This error can happen for many reasons, often due to issues with your setup or how NumPy was installed. We have compiled some common reasons and troubleshooting tips at: https://numpy.org/devdocs/user/troubleshooting-importerror.html Please note and check the following: * The Python version is: Python3.10 from "/usr/local/bin/python3.10" * The NumPy version is: "1.23.5" and make sure that they are the versions you expect. Please carefully study the documentation linked above for further help. Original error was: libpthread.so.0: cannot open shared object file: No such file or directory ne 48, in <module> File "<string>", line 4, in <module> File "/usr/local/lib/python3.10/site-packages/numpy/__init__.py", line 140, in <module> from . import core File "/usr/local/lib/python3.10/site-packages/numpy/core/__init__.py", line 49, in <module> raise ImportError(msg) ImportError: IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE! Importing the numpy C-extensions failed. This error can happen for many reasons, often due to issues with your setup or how NumPy was installed. We have compiled some common reasons and troubleshooting tips at: https://numpy.org/devdocs/user/troubleshooting-importerror.html Please note and check the following: * The Python version is: Python3.10 from "/usr/local/bin/python3.10" * The NumPy version is: "1.23.5" and make sure that they are the versions you expect. Please carefully study the documentation linked above for further help. Original error was: libpthread.so.0: cannot open shared object file: No such file or directory error: exit status 255

this is the sandbox docker log 
![Uploading 1.png…]()

**Comment by sharptornadoqsh** [comment]
![1](https://github.com/user-attachments/assets/c5203c16-b162-49c7-9244-c540830ac5b4)
2024/08/15 06:23:49 setup.go:29: [INFO]initializing nodejs runner environment...
2024/08/15 06:23:50 setup.go:85: [INFO]nodejs runner environment initialized
2024/08/15 06:23:50 setup.go:31: [INFO]initializing python runner environment...
2024/08/15 06:23:50 setup.go:43: [INFO]python runner environment initialized
2024/08/15 06:23:50 config.go:96: [INFO]network has been enabled
2024/08/15 06:23:50 config.go:112: [INFO]using https proxy: http://ssrf_proxy:3128
2024/08/15 06:23:50 config.go:121: [INFO]using http proxy: http://ssrf_proxy:3128
2024/08/15 06:23:50 server.go:20: [INFO]config init success
2024/08/15 06:23:50 server.go:26: [INFO]runner dependencies init success
2024/08/15 06:23:50 server.go:42: [INFO]installing python dependencies...
2024/08/15 06:23:52 setup.go:114: [INFO]Requirement already satisfied: numpy==1.23.5 in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (1.23.5)
2024/08/15 06:23:52 setup.go:114: [INFO]Requirement already satisfied: pypdf==3.17.4 in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (3.17.4)
2024/08/15 06:23:52 setup.go:114: [INFO]Requirement already satisfied: markdown==3.5.2 in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (3.5.2)
2024/08/15 06:23:53 setup.go:135: [INFO]Python dependency installed: numpy 1.23.5
2024/08/15 06:23:53 setup.go:135: [INFO]Python dependency installed: pypdf 3.17.4
2024/08/15 06:23:53 setup.go:135: [INFO]Python dependency installed: markdown 3.5.2
2024/08/15 06:23:53 server.go:48: [INFO]python dependencies installed
2024/08/15 06:23:53 server.go:50: [INFO]initializing python dependencies sandbox...
2024/08/15 06:25:13 server.go:55: [INFO]python dependencies sandbox initialized
2024/08/15 06:25:13 cocrrent.go:31: [INFO]setting max requests to 50
2024/08/15 06:25:13 cocrrent.go:13: [INFO]setting max workers to 4

**Comment by hjlarry** [comment]
follow the FAQ1 add the `libpthread.so.0`

**Comment by sharptornadoqsh** [comment]
> follow the FAQ1 add the `libpthread.so.0`

thank you。i find the problem THE FAQ documnet 's   system call in numpy is wrong

**Comment by hjlarry** [comment]
the document is to show how to resolve the problem,  but the final result is based on different systems

**Comment by Korayem** [comment]
I want to use sandbox to create charts using `pandas` and `matplotlib` but returns errors because packages aren't installed
`line 1, in <module>\nModuleNotFoundError: No module named 'matplotlib'`

So here's what I tried to do in [dify](https://github.com/langgenius/dify/)

1. **Create a custom Dockerfile**:
   Create a new Dockerfile in your `/dif/docker` directory. Named it  `sandbox.dockerfile`.

   ```Dockerfile
    # sandbox.dockerfile
    FROM langgenius/dify-sandbox:latest

    # Copy the requirements.txt file into the container
    COPY sandbox-requirements.txt /dependencies/python-requirements.txt

    # Install the dependencies
    RUN pip3 install --no-cache-dir -r /dependencies/python-requirements.txt
   ```

3. create `docker/sandbox-requirements.txt`

    ```
   matplotlib
   pandas
   ```

3. **Modify the `docker-compose.yaml` to use the custom Dockerfile**:
   Update the `sandbox` service to build from the custom Dockerfile.

   ```yaml
   // ... existing code ...
   sandbox:
     build:
       context: .
       dockerfile: sandbox.dockerfile
     restart: always
     environment:
       # The DifySandbox configurations
       # Make sure you are changing this key for your deployment with a strong key.
       # You can generate a strong key using `openssl rand -base64 42`.
       API_KEY: ${SANDBOX_API_KEY:-dify-sandbox}
       GIN_MODE: ${SANDBOX_GIN_MODE:-release}
       WORKER_TIMEOUT: ${SANDBOX_WORKER_TIMEOUT:-15}
       ENABLE_NETWORK: ${SANDBOX_ENABLE_NETWORK:-true}
       HTTP_PROXY: ${SANDBOX_HTTP_PROXY:-http://ssrf_proxy:3128}
       HTTPS_PROXY: ${SANDBOX_HTTPS_PROXY:-http://ssrf_proxy:3128}
       SANDBOX_PORT: ${SANDBOX_PORT:-8194}
     volumes:
       - ./volumes/sandbox/dependencies:/dependencies
       - ./requirements.txt:/app/requirements.txt  # Mount the requirements.txt file
     networks:
       - ssrf_proxy_network
   // ... existing code ...
   ```

4. **Build and run the updated service**:
   Run the following commands to build and start the updated `sandbox` service.

   ```sh
   docker-compose build sandbox
   docker-compose up sandbox
   ```

This indeed fixes `pandas` and `matplotlib` error but for some reason `numpy` (a dependency of both pandas and matplotlib) is still not found and throws an error
```
Traceback (most recent call last):
File \"/var/sandbox/sandbox-python/tmp/a8bb7065_f87e_4c56_a91e_3d3d6aa23509.py\", line 48, in <module>
File \"<string>\", line 1, in <module>
File \"/usr/local/lib/python3.10/site-packages/pandas/__init__.py\", line 19, in <module>
raise ImportError(ImportError: Unable to import required dependencies: numpy: Error importing numpy: you should not try to import numpy from its source directory; please exit the numpy source tree, and relaunch\n your python interpreter from there.
```

Notice that it read that `pandas` package is installed locally this time, but it can't find its dependency `numpy`, though from the logs when building sandbox with custom `python-requirements.txt,` `numpy` did get installed

I did add `numpy` to `python-requirements.txt` but still the same error showed up

I feel I am so close but don't know what else to do

Thanks in advance
